#!/bin/zsh

updateAConfig() {
    local entry=$1
    local branchName=$2
    local configPath=".aConfig"

    # 檢查並更新配置，或在檔案末尾新增配置
    if awk -v entry="$entry=" -v branchName="$branchName" '
    BEGIN {updated = 0}
    $0 ~ "^" entry {if (!updated) {print entry branchName; updated=1} next}
    {print}
    END {if (!updated) print entry branchName}
    ' "$configPath" > "$configPath.tmp" && mv "$configPath.tmp" "$configPath"; then
        echo "配置更新成功。"
        return 0
    else
        echo "配置更新失敗。"
        return 1
    fi
}

getAConfig(){
  local entry=$1
  local default=$2

  value=$(grep -v '^#' .aConfig 2>/dev/null | grep -m 1 "$entry=" | cut -d'=' -f2-)

  # 若為空字串則回傳預設值
  if [[ -z "$value" ]]; then
    echo "$default"
    return
  fi

  echo "$value"
  return
}