## php多版本
alias php73='"$HOMEBREW_PREFIX"/opt/php@7.3/bin/php'
alias pecl73='"$HOMEBREW_PREFIX"/opt/php@7.3/bin/pecl'
alias composer73='"$HOMEBREW_PREFIX"/opt/php@7.3/bin/php "$HOMEBREW_PREFIX"/bin/composer'
alias php74='"$HOMEBREW_PREFIX"/opt/php@7.4/bin/php'
alias pecl74='"$HOMEBREW_PREFIX"/opt/php@7.4/bin/pecl'
alias composer74='"$HOMEBREW_PREFIX"/opt/php@7.4/bin/php "$HOMEBREW_PREFIX"/bin/composer'
alias php80='"$HOMEBREW_PREFIX"/opt/php@8.0/bin/php'
alias pecl80='"$HOMEBREW_PREFIX"/opt/php@8.0/bin/pecl'
alias composer80='"$HOMEBREW_PREFIX"/opt/php@8.0/bin/php "$HOMEBREW_PREFIX"/bin/composer'
alias php81='"$HOMEBREW_PREFIX"/opt/php@8.1/bin/php'
alias pecl81='"$HOMEBREW_PREFIX"/opt/php@8.1/bin/pecl'
alias composer81='"$HOMEBREW_PREFIX"/opt/php@8.1/bin/php "$HOMEBREW_PREFIX"/bin/composer'
alias php83='"$HOMEBREW_PREFIX"/opt/php@8.3/bin/php'
alias pecl83='"$HOMEBREW_PREFIX"/opt/php@8.3/bin/pecl'
alias composer83='"$HOMEBREW_PREFIX"/opt/php@8.3/bin/php "$HOMEBREW_PREFIX"/bin/composer'
alias hy83='"$HOMEBREW_PREFIX"/opt/php@8.3/bin/php bin/hyperf.php'
# hyperf框架多版本
alias hy80='"$HOMEBREW_PREFIX"/opt/php@8.0/bin/php bin/hyperf.php'
alias hy73='"$HOMEBREW_PREFIX"/opt/php@7.3/bin/php bin/hyperf.php'
alias hy74='"$HOMEBREW_PREFIX"/opt/php@7.4/bin/php bin/hyperf.php'
alias hy='php bin/hyperf.php'